.\"     Title: ngx-conf
.\"    Author: Michael Lustfield <michael@lustfield.net>
.\"      Date: 01/14/2015
.\"    Manual: User Commands
.\"
.TH "NGX-CONF" "1" "01/14/2015" "ngx-conf" "User Commands"
.\" disable hyphenation
.NH
.\" disable justification (adjust text to left margin only)
.AD l
.SH "NAME"
ngx - a tool to help manage nginx confuration files
.SH "SYNOPSIS"
.B ngx-conf
.RI [-h]\ (-e\ CONFIG\ |\ -d\ CONFIG\ |\ -x\ CONFIG\ |\ -l)\ [-f]\ [-r]\ [-v]
.BR
.SH "DESCRIPTION"
.PP
Ngx-conf is a relatively simple tool to help manage Nginx configuration files.
It can be used to enable, disable, remove, and list configuration files.
.SH "OPTIONS"
.PP
This program follows the usual command line syntax, with long options starting
with two dashes (`\-'). A summary of options is included below.
.TP
.B \-h, \-\-help
show a help message and exit
.TP
.B \-e CONFIG, \-\-enable CONFIG
enable a configuration file
.TP
.B \-d CONFIG, \-\-disable CONFIG
disable a configuration file
.TP
.B \-x CONFIG, \-\-remove CONFIG
remove a configuration file; will prompt without -f
.TP
.B \-l, \-\-list
list configuration files
.TP
.B \-f, \-\-force
force change, even if doing so will destroy data
.TP
.B \-r, \-\-reload
reload configuration after change
.TP
.B \-v, \-\-verbose
show verbose output; default is quiet unless errors
.PP
Only one action (enable|disable|edit|remove) can be performed at one time.
However, any action can be specified multiple times.
.SH "EXAMPLES"
.PP
ngx-config -e site1 -e site2 -v -e site3
.BR
ngx-config -r -d site
.BR
ngx-config -f -r -x site1 -x site2
.SH "CONFIGURATION FILES"
.PP
Three configuration files, if present, will be read. They will be read in the
following order; the next read file will always override the previous.
.IP
1. /etc/nginx/ngx.cfg
.BR
2. /etc/ngx.cfg
.BR
3. ngx.cfg
.PP
A sample configuration file with all options set to default:
.IP
[DEFAULT]
.BR
base_dir = /etc/nginx/
.BR
conf_dir = conf.d/
.BR
sites_en = sites-enabled/
.BR
sites_dis = sites-available/
.BR
conf_ext = .conf
.BR
verbose = no
.BR
reload = no
.BR
force = no
.PP
Make sure that base_dir always has a trailing slash.
.BR
Any arguments given to the command will override configuration options.
.SH "BUGS"
.PP
If you experience bugs, the best way to report them is to the upstream bug
tracker. This can be found at https://github.com/ngx/ngx-conf.
.SH "AUTHORS"
.PP
This application and manual page was written by Michael Lustfield <michael@lustfield.net>.
